export { default as Home } from "./Home/Index";
export { default as About } from "./About/Index";
export { default as ContactUs } from "./ContactUs/Index";
export { default as Sell } from "./Seller/Sell/Index";
export { default as Buy } from "./Buyer/Buy/Index";
export { default as Login } from "./Login/Index";
export { default as SignUp } from "./SignUp/Index";
export { default as Card } from "./Cards/Card/Index";
export { default as NotMatch } from "./NotMatch/Index";
